name: UMC Amargetdon CI/CD

on:
  push:
    branches: [ "develop" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    # application.yml file 생성
    - name: make application.yml
      run: 
         cd ./src/main
         cd ./resources
         
         touch ./application.yml
         echo "${{ secrets.YML }}" >> ./application.yml
      shell: bash


    # SpringBoot build
    - name: Build with Gradle 
      run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test


    # docker image build
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest .

    
    # docker login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    # docker image push
    - name: docker hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest


    - name: Docker Run on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker stop $(sudo docker ps -a -q --filter "name=armagetdon-dev") || true
          sudo docker rm $(sudo docker ps -a -q --filter "name=armagetdon-dev") || true
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
          sudo docker run -d —name armagetdon-dev -p 8080:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
 
